### ISSUE TITLE
My Lists are not shown after Creation

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#173]
Description:  When I create my own list as and mark it as private, it is not shown under my lists tab.

Details requested by TA are as below:

Account Used:
Username: rohan.test1
Password: rohan1234

Error: Lists created as private are not shown even to me under my lists tab.

Steps Followed:
(a) Navigate to View Game List tab
(b) Clicked on Make a new Game List
(c) Entered the details, made list as private and got a prompt that list created successfully. 
(d) Navigate to My Lists tab and see nothing. -------------> [ERROR] I should atleast see private lists created by me.
Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/lists/

Expected: I should be able to see game lists created by me, even though I made them private. 
<img width="1470" alt="Screenshot 2024-11-19 at 12 41 13 AM" src="https://github.com/user-attachments/assets/14f2e30c-6c82-4691-a351-2de386be4e50">
<img width="1470" alt="Screenshot 2024-11-19 at 12 42 21 AM" src="https://github.com/user-attachments/assets/eb49ff5d-f4f8-4f10-89ae-277a44f029eb">

I have attached photos and you can see my time as proof.

**Comment by ad6641** [comment]
suspecting the underlying issue is the same as/similar to #174 
closing this one, will update the other one once fixed. Thanks for pointing it out!
