### ISSUE TITLE
Game list created as public not visible under Discover Lists

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#174]
Description: When I create my own list as and mark it as public, it is not shown under discover lists tab.

Details requested by TA are as below:

Account Used:
Username: rohan.test1
Password: rohan1234

Error: Lists created as public are not shown even to me under my lists tab.

Steps Followed:
(a) Navigate to View Game List tab
(b) Clicked on Make a new Game List
(c) Entered the details, made list as public and got a prompt that list created successfully.
(d) Navigate to My Lists tab and see nothing. -------------> [ERROR] I should be able to see public lists created by me under discover lists tab.
Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/lists/

Expected: I should be able to see game lists created by me and other that are public under discover lists tab.
<img width="1470" alt="Screenshot 2024-11-19 at 12 47 57 AM" src="https://github.com/user-attachments/assets/59246a55-125f-4506-99d3-9def3ebaa343">
<img width="1470" alt="Screenshot 2024-11-19 at 12 46 49 AM" src="https://github.com/user-attachments/assets/07984ab6-3764-4a85-85ec-580e78f7562d">

I have attached photos and you can see my time as proof.

**Comment by ad6641** [comment]
Interesting. The lists are being created on our DB, but looks like something's going wrong while fetching it. We'll take a look!

**Comment by ad6641** [comment]
issue identified:
this is an issue with how the Limit keyword works with fetching information from DynamoDB.
Will pick this up this/next sprint!

EDIT
you should be able to see your lists under My Lists now, but because of this issue, at some point once you keep adding more issues, some may not be visible
