### ISSUE TITLE
Event Registered Successful Message Not displayed correctly 

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#176]
Description: When I login as a gamer and click view events and register for an event, I am able to register and gets redirected to event details page.  However, I do not see the message of being registered successfully there as written in testing doc. When I navigate back to the view events tab, then I see the message.

Details requested by TA are as below:

Account Used:
Username: rohan.test1
Password: rohan1234

Error: Not received  a success message.

Steps Followed:
(a) Navigate to View Events tab
(b) Clicked on Event
(c) Registered for the event
(d) Does not get a message that registered successfully on event details page.

Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/events/events/cb0a07e8-4898-4868-9261-1b3a12119d47/

Expected: I should be get a message on event details page that I have been registered successfully for the event.
<img width="1470" alt="Screenshot 2024-11-19 at 2 28 23 PM" src="https://github.com/user-attachments/assets/73ac29a8-e58a-4b17-bd5c-2fd4365b07f5">
<img width="1470" alt="Screenshot 2024-11-19 at 2 28 13 PM" src="https://github.com/user-attachments/assets/7300891d-afb9-490a-9c9a-67d725a8538e">

**Comment by ad6641** [comment]
thanks for pointing this out → you should see yourself in the participants list once you register, but agreed that the message should be shown here rather than when we navigate back to events home page. 
we'll pick this in a later sprint
