### ISSUE TITLE
Not able to delete my own event as event organizer

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#177]
Description: When logged in as event_organizer, I should be able to delete the events created by me, but I'm unable to do so. I cannot find the Delete button when I go to view events page and even when I click on my event.

Details requested by TA are as below:

Account Used:
Username: rohan.test1
Password: rohan1234

Error: Not able to delete events created by me.

Steps Followed:
(a) Navigate to View Events tab
(b) Clicked on Event that was created by me
(c) [ERROR] ----------> Do not see a delete button anywhere.

Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/events/

Expected: I should be able to delete my own events as event_organizer.
<img width="1470" alt="Screenshot 2024-11-19 at 4 29 48 PM" src="https://github.com/user-attachments/assets/41b7e712-7e4b-4829-9a5b-73186463b638">
<img width="1470" alt="Screenshot 2024-11-19 at 4 29 07 PM" src="https://github.com/user-attachments/assets/930a52ed-ab64-4486-872c-9f04630fb61c">

**Comment by ad6641** [comment]
Oversight on our end while typing the doc! thanks again for pointing this out, we have not yet implemented an event delete functionality just yet. 
Closing this since it isn't a bug, but we will update the doc to prevent others from being misled!

**Comment by rohnnie** [comment]
Thank you for acknowledging the oversight in the document. However, since the event delete functionality is explicitly mentioned, this should be considered an enhancement rather than a simple typo. A typo typically refers to a minor error, while this involves a significant functionality. Therefore, I kindly ask you to consider my request as a potential feature enhancement.

**Comment by ad6641** [comment]
I do not think this is a feature "enhancement" - this is a feature that was planned anyway. The document contained information that was not supposed to be there and that's a mistake we are rectifying, and thanks again for pointing this out.

**Comment by ad6641** [comment]
#44

**Comment by rohnnie** [comment]
> #44

All I'm trying to say is, even if it was an open issue, you guys should have not put that functionality into the document. It was there, when I tested, then it was removed and admitted that it was an open issue. The final decision is totally yours, im just pointing out points that are right

**Comment by ZENG-Zhuo** [comment]
Thank you again for bringing this to our attention. I want to clarify that we are removing it from the document to prevent the possibility of multiple duplicated issues, not to diminish your effort in identifying this bug.
