### ISSUE TITLE
Not able to see all Users when filter is All Users

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#178]
Description: I created a new user to test the functionality of friend request. I followed the instructions as given in the document. When I clicked on Friend Requests --> Find Users, im not able to see my other user with name Rohan Chopra (event_organizer) when filter is all roles.

Details requested by TA are as below:

Account Used:
Username: rohan.test2
Password: Rohan1234

Error: Not able to view all users under Friend Requests --> Find Users (All Roles). But, when I filter just by event organizer, then I see my role. The functionality is not working properly for all roles filer.

Steps Followed:
(a) Created a new account with above credentials and logged in 
(b) Clicked on Profile button dropdown and navigate to Friend Requests and then clicked Find Users
(c) [Bug] --> Not able to see my other account user with Rohan Chopra (event_organizer)

Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/profile/search/

Expected: I should be able to see all users regardless of their roles when filtered using all roles. 
![Screenshot 2024-11-19 at 11 00 26 PM](https://github.com/user-attachments/assets/37eb66e8-f3d6-4ef7-a643-a5e29fcca4de)

![Screenshot 2024-11-19 at 11 00 36 PM](https://github.com/user-attachments/assets/28295515-64d5-4162-8149-3dbb84dc3d62)

**Comment by ZENG-Zhuo** [comment]
Thanks for this bug. I think this is because I forgot to implement the paging button and one page can show a maximum of ten results.
