### ISSUE TITLE
500 Error when trying to do SQL injection

### ISSUE THREAD

**Issue by SamuelVRPO** [gcivil-nyu-org/fall24-monday-team1#183]
1. Account used: team3
2. Error encountered: 500 server error
3. Steps to reproduce:
    - Click on 'Search for Game'
    - Enter `'' OR 1 = 1; DROP TABLE Games;` into the search bar
    - Click Search
The table is not actually dropped but I get an 500 error. 
4. Instead of an error, I should get the regular 'No games found' screen.
<img width="1728" alt="Screenshot 2024-11-21 at 12 35 47 PM" src="https://github.com/user-attachments/assets/10a785de-aee0-4d87-9372-ebd1bcc3b39b">
![Screenshot 2024-11-21 at 12 35 47 PM (2)](https://github.com/user-attachments/assets/004fdabb-a3d0-48ac-9399-85bf3419a1c8)
<img width="1728" alt="Screenshot 2024-11-21 at 12 36 04 PM" src="https://github.com/user-attachments/assets/606315c8-1149-44cb-ad38-d275d067e2e6">
![Screenshot 2024-11-21 at 12 36 04 PM (2)](https://github.com/user-attachments/assets/314f4fdd-e6cf-49bd-8506-ba77f41a9cc3)

**Comment by ad6641** [comment]
thanks for raising this bug! identified and fixed this bug in the linked commit. will test and merge with dev and then main once testing party is complete!
