### ISSUE TITLE
CSRF verification failed. Request aborted

### ISSUE THREAD

**Issue by KarthikVV24-11-1999** [gcivil-nyu-org/fall24-monday-team1#189]
<img width="1469" alt="Screenshot 2024-11-21 at 10 19 36 PM" src="https://github.com/user-attachments/assets/c01141cf-5b44-46b0-93dd-6f1ddcaf5068">

Account Used: Karthik
Error: [Forbidden] CSRF verification failed. Request aborted
Steps Followed: 
1. Enter the Login Credentials correctly, but do not click the Login Button yet
2. Click Enter Button on keyboard
3. Quickly change one of the credentials and click Enter again
4. Navigate to the Profile page to see that the user is actually Logged in
5. Log out and Try the above steps again
**Note: In steps 2 and 3, Click "Enter" (a faster way of logging in) 
so that You don't have to use "cursor" for the next steps
However, it can also be reproduced by clicking on Login if you time it correctly**

Expected Results:
- Either the user is logged in as correct credentials are entered 
- Or the error saying that the user credentials are invalid should be shown 

**The issue is encountered when We change the login credentials before it redirects to the profile dashboard, as demonstrated in the video below, but after the  "myProfile" api request is made:**

https://github.com/user-attachments/assets/170be564-f525-4b89-8447-7e6246a57f02

The first login in the video is only to show that the user is actually logged out, and has no other significance

**Comment by ad6641** [comment]
we have tried replicating this on our end and have not encountered this bug. we have tried both of the below steps:
- enter credentials
- hit enter
- quickly change credentials
- hit enter again before page refresh

user logs in normally:

https://github.com/user-attachments/assets/380b023d-6f09-496f-bd16-d445c769295a



- enter credentials
- hit enter
- quickly change credentials
- do NOT hit enter

and the user logs in successfully

https://github.com/user-attachments/assets/a6119613-6341-448c-abeb-dbe902325e9d


this has been tried on Arc, Chrome and Firefox, and we haven't replicated the issue 


closing this out for now, but in case we do still see this in the future, we'll investigate further

**Comment by KarthikVV24-11-1999** [comment]
Hi,

As mentioned in the issue above, 

```The issue is encountered when We change the login credentials before it redirects to the profile dashboard, as demonstrated in the video below, but after the "myProfile" api request is made:```

Please let me know if I can connect with you in a short call to help you replicate this bug on your end

**Comment by KarthikVV24-11-1999** [comment]
@ad6641  I was able to replicate this, reliably, only on the Chrome browser: Here is the video for this whole scenario along with the Network tabs for your understanding of it:

https://github.com/user-attachments/assets/b6e5c18f-2ff3-4360-9bf1-34a4b9f38d60

The above video shows all the possibilities of how the behaviour can be depending on when you click the "enter" button after changing the credentials quickly

Furthermore, Firefox doesn't seem to be affected by this, and Safari does not let me change the password or username however, once it is submitted

**Comment by ad6641** [comment]
thank you for adding more info to this. while i haven't been able to replicate this still, I have preemptively fixed this by disabling the submit button and making the form input fields (both uname and pwd) as readonly once the form is submitted (either by hitting enter or clicking the button)

**Comment by KarthikVV24-11-1999** [comment]
That’s a clever fix, hope to see the changes soon, and eager to test them out again too :)

**Comment by ad6641** [comment]
Feel free to test this out on main now!
