### ISSUE TITLE
Create an account using my email and password

### ISSUE THREAD

**Issue by vikrampentakota** [gcivil-nyu-org/fall24-monday-team1#23]
**Acceptance Criteria**

- Any user (gamer, creator, organizer) can successfully create a profile using their email and password 
- User can specify during sign up their visibility preference and the role they want to sign up as (Gamer, Game Creator, Game Event Organizer)
- If the email already exists, or if password is incorrect, product should handle such cases (usual sign up workflows)
- User must receive a welcome email after successful sign up

**Definition of Done**
Successful sign up for any kind of user, redirecting to the appropriate landing page depending on user role

**Comment by SHREYANSHBHALLA** [comment]
Hi
